#!/usr/bin/env bash
# WhatsApp Claude Bot — First-time setup wizard
# Run once as admin. Creates store/config.sh and initializes store/bot.db.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
STORE_DIR="$SCRIPT_DIR/store"
CONFIG_FILE="$STORE_DIR/config.sh"
BOT_DB="$STORE_DIR/bot.db"

# Resolve binaries
WA_BIN=$(which whatsapp-cli 2>/dev/null || find "$HOME/.local" -name whatsapp-cli 2>/dev/null | head -1)
CLAUDE_BIN=$(which claude 2>/dev/null || echo "$HOME/.local/bin/claude")

if [[ -z "$WA_BIN" ]]; then
  echo "ERROR: whatsapp-cli not found. Install it first."
  echo "  eval \"\$($HOME/.local/bin/mise activate bash)\" && go install github.com/vicentereig/whatsapp-cli@latest"
  exit 1
fi

if [[ -z "$CLAUDE_BIN" ]] || [[ ! -x "$CLAUDE_BIN" ]]; then
  echo "ERROR: claude not found at $CLAUDE_BIN"
  exit 1
fi

echo ""
echo "=== WhatsApp Claude Bot Setup ==="
echo ""

mkdir -p "$STORE_DIR"

# Step 1: Check auth
echo "Checking WhatsApp authentication..."
auth_result=$("$WA_BIN" --store "$STORE_DIR" auth 2>&1)
if echo "$auth_result" | python3 -c "import sys,json; d=json.load(sys.stdin); exit(0 if d.get('data',{}).get('authenticated') else 1)" 2>/dev/null; then
  echo "✓ Already authenticated"
else
  echo "Not authenticated. Showing QR code — scan with WhatsApp on your phone."
  echo "(WhatsApp → Settings → Linked Devices → Link a Device)"
  echo ""
  "$WA_BIN" --store "$STORE_DIR" auth
  echo ""
  echo "✓ Authenticated"
fi

# Step 2: Sync briefly to populate groups
echo ""
echo "Fetching your chats (this takes ~5 seconds)..."
"$WA_BIN" --store "$STORE_DIR" sync &
SYNC_PID=$!
sleep 6
kill $SYNC_PID 2>/dev/null || true
wait $SYNC_PID 2>/dev/null || true

# Step 3: List groups and let user pick
echo ""
read -rp "Search for a group by name (or press Enter to list all): " group_search

groups_json=$("$WA_BIN" --store "$STORE_DIR" chats list --limit 200 2>/dev/null)
mapfile -t group_jids < <(echo "$groups_json" | python3 -c "
import sys, json
data = json.loads(sys.stdin.read())
chats = data.get('data', []) if isinstance(data, dict) else data
search = sys.argv[1].lower() if len(sys.argv) > 1 else ''
groups = [c for c in chats if '@g.us' in c.get('jid','') and (not search or search in c.get('name','').lower())]
for g in groups:
    print(g['jid'])
" "$group_search")
mapfile -t group_names < <(echo "$groups_json" | python3 -c "
import sys, json
data = json.loads(sys.stdin.read())
chats = data.get('data', []) if isinstance(data, dict) else data
search = sys.argv[1].lower() if len(sys.argv) > 1 else ''
groups = [c for c in chats if '@g.us' in c.get('jid','') and (not search or search in c.get('name','').lower())]
for i, g in enumerate(groups, 1):
    print(f\"{i}. {g.get('name', g['jid'])}\")
" "$group_search")

echo ""
echo "Matching WhatsApp groups:"
echo ""

if [[ ${#group_jids[@]} -eq 0 ]]; then
  echo "No groups found. Create a WhatsApp group first, then re-run setup."
  exit 1
fi

for name in "${group_names[@]}"; do
  echo "  $name"
done

echo ""
read -rp "Enter the number of the group to use for the bot: " group_num

if ! [[ "$group_num" =~ ^[0-9]+$ ]] || (( group_num < 1 || group_num > ${#group_jids[@]} )); then
  echo "Invalid selection."
  exit 1
fi

GROUP_JID="${group_jids[$((group_num - 1))]}"
GROUP_NAME="${group_names[$((group_num - 1))]#*. }"
echo "✓ Selected: $GROUP_NAME ($GROUP_JID)"

# Step 4: Bot phone number
echo ""
read -rp "Enter your WhatsApp number with country code (e.g. 919900000000): " phone_number
BOT_JID="${phone_number}@s.whatsapp.net"
echo "✓ Bot JID: $BOT_JID"

# Step 5: Write config.sh
cat > "$CONFIG_FILE" << EOF
# WhatsApp Claude Bot — Config (generated by setup.sh)
# Edit manually if needed, then restart bot.sh

GROUP_JID="$GROUP_JID"
BOT_JID="$BOT_JID"
POLL_INTERVAL=5
WA_BIN="$WA_BIN"
CLAUDE_BIN="$CLAUDE_BIN"
STORE_DIR="$STORE_DIR"
BOT_DB="$STORE_DIR/bot.db"
LOG_FILE="$SCRIPT_DIR/bot.log"
SCRIPT_DIR="$SCRIPT_DIR"
EOF

echo ""
echo "✓ Config written to $CONFIG_FILE"

# Step 6: Initialize bot.db
python3 - "$BOT_DB" << 'PYEOF'
import sqlite3, sys
con = sqlite3.connect(sys.argv[1])
con.execute("""
    CREATE TABLE IF NOT EXISTS processed_messages (
        id TEXT PRIMARY KEY,
        processed_at INTEGER NOT NULL
    )
""")
con.commit()
con.close()
print(f"✓ Bot DB initialized at {sys.argv[1]}")
PYEOF

echo ""
echo "=== Setup complete! ==="
echo ""
echo "To start the bot:"
echo "  bash $SCRIPT_DIR/bot.sh"
echo ""
echo "The bot will respond to messages in '$GROUP_NAME' that start with:"
echo "  !        e.g. \"! what is recursion?\""
echo "  @claude  e.g. \"@claude write a bash script\""
echo ""
